stages:
  - build
  - test
  - deploy

build:
  image: oven/bun:latest
  script:
    - bun install
    - bun build ./index.ts --outdir ./out --target bun
  artifacts:
    paths:
      - build/
       
test:
  image: oven/bun:latest
  script:
    - bun install
    - bun test

deploy:
  image: oven/bun:latest
  script:
    - echo "Deploying to production..."
