name: CI

on: 
    push:
        branches: [main]
    pull_request:
        branches: [main]


jobs:
    build:
        runs-on: ubuntu-latest
         
        steps:
        - uses: actions/checkout@v3
        - name: Use bun.js 18.x
          uses: oven-sh/setup-bun@v2
        
        - run: bun install
        - run: bun run build

   